name: MSBuild for PR
on: 
  pull_request:

env:
  REPODB_MYSQL_CONSTR_SYS: "Server=127.0.0.1;Port=43306;Database=sys;User ID=root;Password=ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2;"
  REPODB_ORACLE_CONSTR_MASTER: "Data Source=127.0.0.1:41521/FREEPDB1;User Id=system;Password=oracle;"
  REPODB_POSTGRESQL_CONSTR_POSTGRESDB: "Server=127.0.0.1;Port=45432;Database=postgres;User Id=postgres;Password=ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2;"
  REPODB_SQLSERVER_CONSTR_MASTER: "Server=tcp:127.0.0.1,41433;Database=master;User ID=sa;Password=ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2;TrustServerCertificate=True;"

jobs:
  build:
    runs-on: ubuntu-latest

    # Services. See docker-compose.yml
    services:
        mysql:
          image: mysql:latest
          ports:
            - 127.0.0.1:43306:3306
          env:
            MYSQL_ROOT_PASSWORD: ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2

        oracle:
           image: gvenzl/oracle-free:23-slim-faststart
           ports:
            - 127.0.0.1:41521:1521
            - 127.0.0.1:45500:5500
           env:
             ORACLE_PASSWORD: "oracle"
             ORACLE_ALLOW_REMOTE: "true"

        postgresql:
          image: postgres:17-alpine
          ports:
            - 127.0.0.1:45432:5432
          env:
            POSTGRES_PASSWORD: ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2

        sqlserver:
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - 127.0.0.1:41433:1433
          env:
            ACCEPT_EULA: true
            MSSQL_SA_PASSWORD: ddd53e85-b15e-4da8-91e5-a7d3b00a0ab2

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup DotNet Versions
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: build
        run: dotnet build -c Release

        # Workaround for DotNet 10.0 SDK issue. Use response file to run tests
      - name: Create dotnet test response file
        run: |
          echo "-c Release" > test.rsp
          echo "-f net10.0" >> test.rsp
          echo "--no-build" >> test.rsp
          echo "-p:TestingPlatformShowTestsFailure=true" >> test.rsp
          echo "-p:TestingPlatformCaptureOutput=false" >> test.rsp

      - name: Run tests for DotNet 10.0
        run: dotnet test @test.rsp

      - name: Pack packages
        run: dotnet pack -c Release -p Version="1.15.0-dev-${{ github.run_number }}" -p PackagePrefix=AmpScm. -o release

      - name: Package nupkg files
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/*nupkg
